export async function deployToGitHubPages(
  html: string,
  repoName: string,
  githubToken: string,
  githubLogin: string
): Promise<string> {
  const headers = {
    Authorization: `Bearer ${githubToken}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  }
  const owner = githubLogin

  // 1. Create repo (ignore 422 = already exists)
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      auto_init: true,
      private: false,
      description: 'Portfolio generated by ResumeFolio',
    }),
  })
  if (!createRes.ok && createRes.status !== 422) {
    const err = await createRes.json()
    throw new Error(`Failed to create repo: ${err.message}`)
  }

  // Brief wait for repo init if newly created
  if (createRes.ok) {
    await new Promise((r) => setTimeout(r, 2000))
  }

  // 2. Get SHA of existing index.html (required for updates)
  const existingRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/contents/index.html`,
    { headers }
  )
  const existing = existingRes.ok ? await existingRes.json() : null

  // 3. Create or update index.html
  const putBody: Record<string, unknown> = {
    message: 'Update portfolio via ResumeFolio',
    content: Buffer.from(html).toString('base64'),
    branch: 'main',
  }
  if (existing?.sha) putBody.sha = existing.sha

  const putRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/contents/index.html`,
    { method: 'PUT', headers, body: JSON.stringify(putBody) }
  )
  if (!putRes.ok) {
    const err = await putRes.json()
    throw new Error(`Failed to push index.html: ${err.message}`)
  }

  // 4. Enable GitHub Pages (ignore 409 = already enabled)
  const pagesRes = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/pages`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({ source: { branch: 'main', path: '/' } }),
    }
  )
  if (!pagesRes.ok && pagesRes.status !== 409) {
    // 409 means Pages already enabled — that's fine
    const err = await pagesRes.json()
    // Non-fatal: log but don't throw (pages may need manual enable on free accounts)
    console.warn('GitHub Pages enable warning:', err.message)
  }

  return `https://${owner}.github.io/${repoName}`
}

export async function deleteGitHubRepo(
  repoName: string,
  githubToken: string,
  githubLogin: string
): Promise<void> {
  const res = await fetch(`https://api.github.com/repos/${githubLogin}/${repoName}`, {
    method: 'DELETE',
    headers: {
      Authorization: `Bearer ${githubToken}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
  })
  // 204 = deleted, 404 = already gone — both are fine
  if (!res.ok && res.status !== 404) {
    const err = await res.json().catch(() => ({}))
    throw new Error(`Failed to delete repo: ${err.message ?? res.status}`)
  }
}

export async function checkPageLive(url: string): Promise<boolean> {
  try {
    const res = await fetch(url, { method: 'HEAD' })
    return res.ok
  } catch {
    return false
  }
}

export function slugifyRepoName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80) || 'my-portfolio'
}
